--01_revenue_by_category.sql
--What is the total revenue generated by each product category?
-- Key Insight: Beverages dominate with ~24.55% of total revenue → high concentration risk
-- Business Impact: Supply issues in Beverages could severely affect overall sales
-- Recommendation: Protect supply chain + promote diversification
select  
		category,
		sum(f.total_price) as total_revenue , round(sum(f.total_price) *100.0 / sum(sum(f.total_price)) over(),2) as perc_value
from item i
join fact_table f on i.item_id = f.item_id
group by 1 
order by total_revenue desc;
